- arguments: [--cpp-define=HLINT, --cpp-ansi]
- ignore: { name: Use camelCase }
- fixity: "infixl 9 :>"
- fixity: "infixr 9 <.>, <., .>, ..."
- fixity: "infixr 9 #."
- fixity: "infixl 8 ^.., ^?, ^?!, ^@.., ^@?, ^@?!,  ^., ^@.,  ^#, .#"
- fixity: "infixr 8 ^!, ^@!"
- fixity: "infixr 4 </>~, <</>~, <.>~, <<.>~, <#~, #~, #%~, <#%~, #%%~, .|.~, .&.~, <.|.~, <.&.~, %@~, .~, +~, *~, -~, //~, ^~, ^^~, **~, &&~, <>~, ||~, %~, %%@~, <%@~, %%~, <+~, <*~, <-~, <//~, <^~, <^^~, <**~"
- fixity: "infix 4 </>=, <</>=, <.>=, <<.>=, <#=, #=, #%=, <#%=, #%%=, .|.=, .&.=, <.|.=, <.&.=, %@=, .=, +=, *=, -=, //=, ^=, ^^=, **=, &&=, <>=, ||=, %=, %%@=, <%@=, %%=, <+=, <*=, <-=, <//=, <^=, <^^=, <**="
- fixity: "infixr 2 `zoom`, `magnify`, <~, <<~"
- fixity: "infixl 1 &, &~, <&>, ??"
