name: Haskell CI

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: [9.2.2, 8.6.5]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
    - name: Install cabal
      run: ghcup install cabal recommended
    - name: Install GHC
      run: ghcup install ghc ${{matrix.ghc}}
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run:  cabal update
    - name: Build
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all